print("COMMANDS THAT START WITH ! :")
print("	!help -- shows list of commands")
print("	!credits -- prints out credits")
print("	!ver -- prints out version of termi")
print("	!exit -- exits Termi")
print("Calculator commands :")
print("	Opencalc -- opens a calculator")
print("	OpenGeocalc -- opens a geometric calculator")
print("Filesys commands : // WORK IN PROGRESS")
print("	createf -- creates a file")
print("	openf -- opens a file")
print("	cd -- cds into a direcotry")
print("	rm -- removes a file/directory")
print("	mkdir -- creates a directory")
print(" list -- lists files in a directory\n")
print("|-------------------------------------------|")